# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - tco-web-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          cd test-app
          npm install
          npm run build --if-present
          # npm run test --if-present
          
      - name: Deploy to Github Pages  
        uses: JamesIves/github-pages-deploy-action@releases/v2
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN}}
          BASE_BRANCH: main
          BRANCH: prod
          FOLDER: test-app/dist/browser
